// Which printer a .3mf says it is for.
//
// Every case here comes from building a real-shaped slicer file and reading what came back, after a
// hand-made PrusaSlicer 3mf returned `brand: null` for an MK4S — Prusa's current flagship. Run: `npm test`.
import { test } from "node:test";
import assert from "node:assert/strict";
import { zipSync, strToU8 } from "fflate";
import { detectProfile } from "./convert.ts";

/** A PrusaSlicer .3mf: an INI at Metadata/Slic3r_PE.config. */
const prusa = (model: string, settingsId?: string) =>
  new File(
    [
      zipSync({
        "Metadata/Slic3r_PE.config": strToU8(
          `printer_model = ${model}\n` + (settingsId ? `printer_settings_id = ${settingsId}\n` : ""),
        ),
      }),
    ],
    "x.3mf",
  );

/** A Bambu/Orca/Snapmaker-Orca .3mf: JSON at Metadata/project_settings.config. */
const orca = (o: Record<string, unknown>) =>
  new File([zipSync({ "Metadata/project_settings.config": strToU8(JSON.stringify(o)) })], "x.3mf");

test("Prusa's current models are recognised, not just the older ones", async () => {
  // MK4S, MK4IS, MINIIS and COREONE all returned brand=null before: `\bmk[234]\b` needs a word
  // boundary straight after the digit, and "MK4S" has none. These are the machines people own now.
  for (const m of ["MK4S", "MK4IS", "MK3.9", "MK4", "XL", "MINIIS", "COREONE", "MINI+"]) {
    const r = await detectProfile(prusa(m, `Original Prusa ${m} 0.4 nozzle`));
    assert.equal(r.hasProfile, true, m);
    assert.equal(r.brand, "Prusa", `${m} resolved to ${r.brand}`);
    assert.equal(r.printer, m);
  }
});

test("the vendor is read from printer_settings_id when the model code alone is unknown", async () => {
  // printer_model is a bare code; printer_settings_id spells the vendor out. Keeping it means the
  // brand survives for a model this code has never heard of — the point of not being tied to one.
  const r = await detectProfile(prusa("SOMETHING-UNRELEASED-9000", "Original Prusa Something 0.4 nozzle"));
  assert.equal(r.hasProfile, true);
  assert.equal(r.brand, "Prusa");
});

test("a profile with no recognisable vendor still verifies, with no brand invented", async () => {
  const r = await detectProfile(prusa("WIDGETRON-1"));
  assert.equal(r.hasProfile, true, "it is still a real, print-ready profile");
  assert.equal(r.brand, null, "and a brand must not be guessed");
});

test("the U1 is unaffected by opening this up", async () => {
  const r = await detectProfile(orca({ printer_model: "Snapmaker U1" }));
  assert.equal(r.brand, "Snapmaker");
  assert.equal(r.isU1, true);
});

test("other brands still resolve", async () => {
  for (const [model, brand] of [
    ["Bambu Lab X1 Carbon", "Bambu"],
    ["Creality K1 Max", "Creality"],
    ["Elegoo Neptune 4", "Elegoo"],
    ["Anycubic Kobra 3", "Anycubic"],
  ] as const) {
    const r = await detectProfile(orca({ printer_model: model }));
    assert.equal(r.brand, brand, `${model} -> ${r.brand}`);
  }
});

test("a file with no slicer profile is not verifiable on any printer", async () => {
  // The actual quality bar, unchanged by the pivot: plain geometry is what makes multicolour prints
  // fail, and it fails everywhere.
  const bare = new File([zipSync({ "3D/3dmodel.model": strToU8("<model/>") })], "x.3mf");
  const r = await detectProfile(bare);
  assert.equal(r.hasProfile, false);
  assert.equal(r.brand, null);
});

// ── A REAL PrusaSlicer FILE, NOT A TWO-LINE ONE — ported from the library repo 2026-08-27 ────────
//
// The `prusa()` helper above writes exactly the keys under test, one per line, with nothing else in
// the file. Every case above passes against an UNANCHORED reader, which is what this file had, and
// what every Prusa file in the library's `samples/` came back wrong from.
//
// A real Slic3r_PE.config is a commented-out INI of ~250 lines, and both keys have a DECOY that
// sorts ahead of them:
//
//   ; compatible_printers_condition_cummulative = "printer_model=~/(COREONE…)/ and …"   ← line 34
//   ; physical_printer_settings_id =                                                     ← empty
//
// `printer_model` returned three hundred characters of slicer expression. `printer_settings_id`
// failed worse: `\s` matches a newline, so on the empty `physical_` line `\s*` swallowed the break
// and `(.+)` captured the NEXT line — the brand fallback resolved to the literal `"; post_process ="`.
//
// The library repo fixed this on 2026-08-27 (makerrun #276) after running detectProfile over real
// files for the first time. detectProfile has no production caller HERE — this repo's /api/* rewrites
// to the library, which does the detecting — so the bug was never live on bedready.io. It was public,
// and tested, and wrong, which is its own kind of cost in an open repository.
const realistic = (model: string, settingsId: string) =>
  new File(
    [
      zipSync({
        "Metadata/Slic3r_PE.config": strToU8(
          [
            "; generated by PrusaSlicer 2.9.2 on 2026-08-27",
            "; avoid_crossing_perimeters = 0",
            `; compatible_printers_condition_cummulative = "printer_model=~/(${model}|MK4S|MK4IS)/ and nozzle_diameter[0]==0.4 and ! single_extruder_multi_material";"printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_model!~/(MINI|MK25|MK3)/"`,
            "; first_layer_height = 0.2",
            "; physical_printer_settings_id = ",
            "; post_process = ",
            `; printer_model = ${model}`,
            "; printer_notes = Don't remove the following keywords!",
            `; printer_settings_id = ${settingsId}`,
            "; printer_variant = 0.4",
          ].join("\n"),
        ),
      }),
    ],
    "x.3mf",
  );

test("the printer is the printer, not the compatibility condition that names it first", async () => {
  const r = await detectProfile(realistic("COREONE", "Original Prusa CORE One HF0.4 nozzle"));
  assert.equal(r.printer, "COREONE", `read ${JSON.stringify(r.printer?.slice(0, 60))}…`);
  assert.ok(!r.printer!.includes("=~/"), "a compatibility expression is not a printer name");
  assert.ok(r.printer!.length < 40, `a printer name is short; got ${r.printer!.length} characters`);
  assert.equal(r.brand, "Prusa");
  assert.equal(r.isU1, false);
  assert.equal(r.foreign, true);
});

test("an EMPTY physical_printer_settings_id does not swallow the next line", async () => {
  // The decoy contains `printer_settings_id` as a substring AND has no value, so an unanchored
  // `\s*(.+)` crossed the line break and captured `; post_process =`. The brand then came from that.
  const r = await detectProfile(realistic("MK4S", "Original Prusa MK4S 0.4 nozzle"));
  assert.equal(r.brand, "Prusa", "the brand must come from the real key, not the line after a decoy");
  assert.equal(r.printer, "MK4S");
});

test("the brand survives a model this code has never heard of", async () => {
  // The point of the settings_id fallback: printer_model is a bare code, and an unreleased one
  // resolves to no brand on its own. It must still be found in the file, past the decoys.
  const r = await detectProfile(realistic("WIDGETRON-9000", "Original Prusa Widgetron 9000 0.4 nozzle"));
  assert.equal(r.printer, "WIDGETRON-9000");
  assert.equal(r.brand, "Prusa", "resolved from printer_settings_id");
});

test("a key with no value is no match, rather than a match on nothing", async () => {
  const bare = new File(
    [zipSync({ "Metadata/Slic3r_PE.config": strToU8("; printer_model = \n; printer_settings_id = \n") })],
    "x.3mf",
  );
  const r = await detectProfile(bare);
  assert.equal(r.hasProfile, true, "the file still declares a Prusa profile");
  assert.equal(r.printer, null, "an empty value is not a printer name");
  assert.equal(r.brand, null);
});
