import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

export default [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // Relaxed rules to establish the gate on a never-before-linted codebase without a mass refactor.
    // These fire heavily on existing, working code; downgraded to warn/off so `next build` stays green.
    // TIGHTEN LATER once the backlog is worked down.
    rules: {
      // The app intentionally uses <img> for user-uploaded/remote/SVG assets (see eslint-disable
      // comments already in several files); next/image isn't a fit everywhere. Warn, don't block.
      "@next/next/no-img-element": "warn",
      // Pragmatic `any` in Supabase row casts and 3mf/color parsing. Off for now.
      "@typescript-eslint/no-explicit-any": "off",
      // Noisy across parsers/handlers with intentionally-unused args. Warn only.
      "@typescript-eslint/no-unused-vars": "warn",
    },
  },
  {
    // Error boundaries intentionally use a plain <a href="/"> for a full reload-to-recover.
    // `global-error` in particular renders its own <html>/<body> and cannot use the app-router
    // <Link/>. Disable the pages-link rule for these files only.
    files: ["src/app/**/error.tsx", "src/app/**/global-error.tsx"],
    rules: { "@next/next/no-html-link-for-pages": "off" },
  },
  // Global ignores (an object with ONLY `ignores` applies repo-wide in flat config).
  // next-env.d.ts is auto-generated by Next and must keep its triple-slash reference.
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "extension/**",
      "**/*.mjs",
      "next-env.d.ts",
      // Not app source, and each of these made `npm run lint` unusable by burying real findings:
      // together they reported ~2,000 errors while `eslint src` was completely clean.
      ".claude/**", // agent scratch space — and git worktrees live here, so this is the whole repo again, N times over
      // CI checks out the DESKTOP APP here so engine-parity.test.mts can compare the two
      // implementations (see .github/workflows/ci.yml). It is a different project with its
      // own lint rules — `eslint .` reported 1,671 problems from it and failed the build.
      // Not ours to lint; the app repo lints itself.
      ".khayt-app/**",
      "safari/**", // Xcode project for the Safari extension (gitignored); vendored JS, not ours to lint
      ".safari-src/**",
      // Written by the Supabase CLI when a local stack is running — the bundled edge-runtime source,
      // gitignored and not ours. It appears only on a machine that has run `supabase start`, which is
      // why CI never saw it: 154 errors and 32 warnings, all from one vendored file, on exactly the
      // machine where somebody is trying to verify something locally.
      "supabase/.temp/**",
    ],
  },
];
